/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author dias
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescriptioin = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldDescription = new javax.swing.JTextField();
        fieldAvailability = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        lblManufactureAddress = new javax.swing.JLabel();
        lblShippingAddress = new javax.swing.JLabel();
        lblManAddrZipCode = new javax.swing.JLabel();
        fieldManAddrZipCode = new javax.swing.JTextField();
        fieldManAddrCity = new javax.swing.JTextField();
        lblManAddrCity = new javax.swing.JLabel();
        lblManAddrUnitNumber = new javax.swing.JLabel();
        fieldManAddrUnitNumber = new javax.swing.JTextField();
        fieldManAddrStreetName = new javax.swing.JTextField();
        lblManAddrStreetName = new javax.swing.JLabel();
        fieldShipAddrZipCode = new javax.swing.JTextField();
        fieldShipAddrCity = new javax.swing.JTextField();
        lblShipAddrCity = new javax.swing.JLabel();
        lblShipAddrUnitNumber = new javax.swing.JLabel();
        fieldShipAddrUnitNumber = new javax.swing.JTextField();
        fieldShipAddrStreetName = new javax.swing.JTextField();
        lblShipAddrStreetName = new javax.swing.JLabel();
        lblShipAddrZipCode = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lblTitle.setText("CREATE A PRODUCT");

        lblName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblName.setText("Name");

        lblDescriptioin.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblDescriptioin.setText("Description");

        lblAvailability.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblAvailability.setText("Availability");

        lblPrice.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblPrice.setText("Price");

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        fieldDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescriptionActionPerformed(evt);
            }
        });

        lblManufactureAddress.setText("Manufacture Address");

        lblShippingAddress.setText("Shipping Address");

        lblManAddrZipCode.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblManAddrZipCode.setText("Zip Code");

        lblManAddrCity.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblManAddrCity.setText("City");

        lblManAddrUnitNumber.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblManAddrUnitNumber.setText("Unit number");

        fieldManAddrUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManAddrUnitNumberActionPerformed(evt);
            }
        });

        fieldManAddrStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManAddrStreetNameActionPerformed(evt);
            }
        });

        lblManAddrStreetName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblManAddrStreetName.setText("Street name");

        lblShipAddrCity.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblShipAddrCity.setText("City");

        lblShipAddrUnitNumber.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblShipAddrUnitNumber.setText("Unit number");

        fieldShipAddrUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShipAddrUnitNumberActionPerformed(evt);
            }
        });

        fieldShipAddrStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShipAddrStreetNameActionPerformed(evt);
            }
        });

        lblShipAddrStreetName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblShipAddrStreetName.setText("Street name");

        lblShipAddrZipCode.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblShipAddrZipCode.setText("Zip Code");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblDescriptioin)
                            .addComponent(lblAvailability)
                            .addComponent(lblPrice))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldName)
                            .addComponent(fieldDescription)
                            .addComponent(fieldAvailability)
                            .addComponent(fieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManAddrStreetName)
                                    .addComponent(lblManAddrUnitNumber)
                                    .addComponent(lblManAddrCity)
                                    .addComponent(lblManAddrZipCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldManAddrStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(fieldManAddrUnitNumber)
                                    .addComponent(fieldManAddrCity)
                                    .addComponent(fieldManAddrZipCode)))
                            .addComponent(lblManufactureAddress))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShippingAddress)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblShipAddrStreetName)
                                    .addComponent(lblShipAddrUnitNumber)
                                    .addComponent(lblShipAddrCity)
                                    .addComponent(lblShipAddrZipCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldShipAddrStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(fieldShipAddrUnitNumber)
                                    .addComponent(fieldShipAddrCity)
                                    .addComponent(fieldShipAddrZipCode)))))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptioin)
                    .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(fieldAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureAddress)
                    .addComponent(lblShippingAddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManAddrStreetName)
                            .addComponent(fieldManAddrStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManAddrUnitNumber)
                            .addComponent(fieldManAddrUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManAddrCity)
                            .addComponent(fieldManAddrCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManAddrZipCode)
                            .addComponent(fieldManAddrZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShipAddrStreetName)
                            .addComponent(fieldShipAddrStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShipAddrUnitNumber)
                            .addComponent(fieldShipAddrUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShipAddrCity)
                            .addComponent(fieldShipAddrCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShipAddrZipCode)
                            .addComponent(fieldShipAddrZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescriptionActionPerformed

    private void fieldManAddrUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManAddrUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManAddrUnitNumberActionPerformed

    private void fieldManAddrStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManAddrStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManAddrStreetNameActionPerformed

    private void fieldShipAddrUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShipAddrUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShipAddrUnitNumberActionPerformed

    private void fieldShipAddrStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShipAddrStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShipAddrStreetNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        String name = fieldName.getText();
        String description = fieldDescription.getText();
        String avail = fieldAvailability.getText();
        String price = fieldPrice.getText();
        
        String manStreet = fieldManAddrStreetName.getText();
        String manUnit = fieldManAddrUnitNumber.getText();
        String manCity = fieldManAddrCity.getText();
        String manZip = fieldManAddrZipCode.getText();
        
        String shipStreet = fieldShipAddrStreetName.getText();
        String shipUnit = fieldShipAddrUnitNumber.getText();
        String shipCity = fieldShipAddrCity.getText();
        String shipZip = fieldShipAddrZipCode.getText();
        
        product.setName(name);
        product.setDescription(description);
        product.setAvailNum(avail);
        product.setPrice(price);
        
        product.getManufactureAddress().setStreetName(manStreet);
        product.getManufactureAddress().setUnitNum(manUnit);
        product.getManufactureAddress().setCity(manCity);
        product.getManufactureAddress().setZipCode(manZip);
        
        product.getShippingAddress().setStreetName(shipStreet);
        product.getShippingAddress().setUnitNum(shipUnit);        
        product.getShippingAddress().setCity(shipCity);        
        product.getShippingAddress().setZipCode(shipZip);        
        
        
        JOptionPane.showMessageDialog(this,"SAVED");
        
        fieldName.setText("");
        fieldAvailability.setText("");
        fieldDescription.setText("");
        fieldPrice.setText("");
        
        fieldManAddrCity.setText("");
        fieldManAddrStreetName.setText("");
        fieldManAddrUnitNumber.setText("");
        fieldManAddrZipCode.setText("");
        
        fieldShipAddrCity.setText("");
        fieldShipAddrStreetName.setText("");
        fieldShipAddrUnitNumber.setText("");
        fieldShipAddrZipCode.setText("");

        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvailability;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldManAddrCity;
    private javax.swing.JTextField fieldManAddrStreetName;
    private javax.swing.JTextField fieldManAddrUnitNumber;
    private javax.swing.JTextField fieldManAddrZipCode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShipAddrCity;
    private javax.swing.JTextField fieldShipAddrStreetName;
    private javax.swing.JTextField fieldShipAddrUnitNumber;
    private javax.swing.JTextField fieldShipAddrZipCode;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblDescriptioin;
    private javax.swing.JLabel lblManAddrCity;
    private javax.swing.JLabel lblManAddrStreetName;
    private javax.swing.JLabel lblManAddrUnitNumber;
    private javax.swing.JLabel lblManAddrZipCode;
    private javax.swing.JLabel lblManufactureAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShipAddrCity;
    private javax.swing.JLabel lblShipAddrStreetName;
    private javax.swing.JLabel lblShipAddrUnitNumber;
    private javax.swing.JLabel lblShipAddrZipCode;
    private javax.swing.JLabel lblShippingAddress;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
