/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author dias
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    VitalSignHistory history;
    
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblPressure = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemp = new javax.swing.JTextField();
        fieldPressure = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        radioBtnYes = new javax.swing.JRadioButton();
        radioBtnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        jLabel1.setText("Create Vital Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblStatus.setText("Conscious Status");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblTemp.setText("Temperature");
        add(lblTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblPressure.setText("Blood Pressure");
        add(lblPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        fieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDateActionPerformed(evt);
            }
        });
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, -1));
        add(fieldTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));
        add(fieldPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, -1));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        btnGroup.add(radioBtnYes);
        radioBtnYes.setSelected(true);
        radioBtnYes.setText("Yes");
        add(radioBtnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        btnGroup.add(radioBtnNo);
        radioBtnNo.setText("No");
        add(radioBtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 420, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String date = fieldDate.getText().trim();
        if (date.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        float temp;
        double pressure;
        int pulse;
        try {
            temp = Float.parseFloat(fieldTemp.getText().trim());
            pressure = Double.parseDouble(fieldPressure.getText().trim());
            pulse = Integer.parseInt(fieldPulse.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Temperature, pressure and pulse must be numbers",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean isConscious;
        
        if(radioBtnYes.isSelected()){ 
            isConscious = true;
        } else {
            isConscious = false;
        }
        
        
        
        VitalSign vs = history.addNewVital();
        
        vs.setDate(date);
        vs.setTemperature(temp);
        vs.setBloodPressure(pressure);
        vs.setPulse(pulse);
        vs.setIsConcious(isConscious);
        
        JOptionPane.showMessageDialog(this, "New VitalSign added", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        
        fieldDate.setText("");
        fieldTemp.setText("");
        fieldPressure.setText("");
        fieldPulse.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private boolean isBlank(String text){
        return text == null || text.trim().isEmpty();
    }
    
    private boolean require(String value, String label){
        if(isBlank(value)){
            JOptionPane.showMessageDialog(this,label + " is required");
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPressure;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JRadioButton radioBtnNo;
    private javax.swing.JRadioButton radioBtnYes;
    // End of variables declaration//GEN-END:variables
}
