/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dias
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    VitalSignHistory history;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.setRowCount(0);
        
        for(VitalSign vs: history.getHistory()){
            Object[] row = new Object[5];
            row[0] = vs;
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodPressure();
            row[3] = vs.getPulse();
            row[4] = vs.isIsConcious();
            
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTital = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblPressure = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemp = new javax.swing.JTextField();
        fieldPressure = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblConcious = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTital.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        lblTital.setText("View Vital Sign");
        jPanel1.add(lblTital, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        lblStatus.setText("Conscious Status");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        lblDate.setText("Date");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        lblTemp.setText("Temperature");
        jPanel1.add(lblTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lblPressure.setText("Blood Pressure");
        jPanel1.add(lblPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lblPulse.setText("Pulse");
        jPanel1.add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        fieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDateActionPerformed(evt);
            }
        });
        jPanel1.add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 140, -1));
        jPanel1.add(fieldTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 140, -1));
        jPanel1.add(fieldPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 140, -1));
        jPanel1.add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 140, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "Blood Pressure", "Pulse", "Conscious Status"
            }
        ));
        scrollPane.setViewportView(table);

        jPanel1.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 210));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));
        jPanel1.add(lblConcious, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        history.deleteVital(selectedVital);
        
        JOptionPane.showMessageDialog(this, "Vital sign deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        populateTable();
        
        fieldDate.setText("");
        fieldTemp.setText("");
        fieldPressure.setText("");
        fieldPulse.setText("");
        lblConcious.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        if(selectedVital != null){
            fieldDate.setText(selectedVital.getDate());
            fieldTemp.setText(String.valueOf(selectedVital.getTemperature()));
            fieldPressure.setText(String.valueOf(selectedVital.getBloodPressure()));
            fieldPulse.setText(String.valueOf(selectedVital.getPulse()));
            
            if(selectedVital.isIsConcious()){
                lblConcious.setText("Yes");
            } else {
                lblConcious.setText("No");
            }
            
            
            
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPressure;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConcious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTital;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
